channel: Welcome back my friend
crdroidandroid/local_manifests pull request #164
Opened 2024-11-18 15:32 UTC by L1ghtzin

2024-11-18 17:38 UTC, gwolf2u requested changes
missing repo
https://github.com/crdroidandroid/android_device_motorola_channel/blob/14.0/crdroid.dependencies#L8

2024-11-18 17:39 UTC, gwolf2u commented
do validate locally by deleting roomservice.xml file, repo sync and brunch device
it'll pull all dependencies if set properly

2024-11-18 19:12 UTC, L1ghtzin commented
fixed

2024-11-19 11:49 UTC, gwolf2u approved these changes

2024-11-19 11:50 UTC, merged